In [7]:
import torch

# 假设ego_future包含3个未来时间步的[x, y, θ]
ego_future = torch.tensor([
    [10.0, 20.0, 0.7854],  # θ=π/4 (45度)
    [15.0, 25.0, 1.5708],  # θ=π/2 (90度)
    [20.0, 30.0, 3.1416],  # θ=π (180度)
])

try_stack = torch.stack(
                    [ego_future[..., 2], ego_future[..., 2]], dim=-1
                )

# 提取朝向角并转换为方向向量
ego_future = torch.cat(
            [
                ego_future[..., :2],
                try_stack,
            ],
            dim=-1,
            )
print("原始角度(弧度):")
print(ego_future[..., 2].size(), ego_future[..., 2])

print("try_stack:")
print(try_stack.size(), try_stack)

print("after ego_future:")
print(ego_future.size(), ego_future)


原始角度(弧度):
tensor([0.7854, 1.5708, 3.1416])
try_stack:
tensor([[0.7854, 0.7854],
        [1.5708, 1.5708],
        [3.1416, 3.1416]])
after ego_future:
tensor([[10.0000, 20.0000,  0.7854,  0.7854],
        [15.0000, 25.0000,  1.5708,  1.5708],
        [20.0000, 30.0000,  3.1416,  3.1416]])


In [20]:
a = torch.randn(3, 2)  
b = torch.randn(3, 4)  
acatb = torch.cat([a, b], dim=-1)  # 沿第-1维拼接，其他维度形状相同，合法

print('a:', a.size(), a)
print('b:', b.size(), b)
print('acatb:', acatb.size(), acatb)


a = torch.randn(1, 3)  
b = torch.randn(1, 3)  
astackb = torch.stack([a,b], dim=0)    # 所有输入张量形状必须完全相同, 在哪个维度stack就增加一个维度
print('a:', a.size(), a)
print('b:', b.size(), b)
print('astackb:', astackb.size(), astackb)  #astackb: torch.Size([2, 1, 3])
astackb = torch.stack([a,b], dim=-1) 
print('astackb:', astackb.size(), astackb)  #astackb: torch.Size([1, 3, 2])

a: torch.Size([3, 2]) tensor([[ 0.2067,  1.4989],
        [-0.4297, -1.5362],
        [-0.8278, -1.4167]])
b: torch.Size([3, 4]) tensor([[ 0.5906,  0.7354,  0.1553, -0.6914],
        [ 0.6410, -0.0033, -0.7739,  0.5996],
        [-0.0810, -0.8909,  0.5481, -1.4936]])
acatb: torch.Size([3, 6]) tensor([[ 0.2067,  1.4989,  0.5906,  0.7354,  0.1553, -0.6914],
        [-0.4297, -1.5362,  0.6410, -0.0033, -0.7739,  0.5996],
        [-0.8278, -1.4167, -0.0810, -0.8909,  0.5481, -1.4936]])
a: torch.Size([1, 3]) tensor([[-0.1426, -1.9374,  0.6408]])
b: torch.Size([1, 3]) tensor([[-1.0912,  0.4484, -0.5828]])
astackb: torch.Size([2, 1, 3]) tensor([[[-0.1426, -1.9374,  0.6408]],

        [[-1.0912,  0.4484, -0.5828]]])
astackb: torch.Size([1, 3, 2]) tensor([[[-0.1426, -1.0912],
         [-1.9374,  0.4484],
         [ 0.6408, -0.5828]]])


In [3]:
import numpy as np
import torch
ego_current = np.array([1, 2, 3])   # 形状：(3, )表示一维数组
result = ego_current[:, None]  # 形状：(3, 1)
# 等价于：
result = ego_current.reshape(-1, 1)  # NumPy 或 PyTorch 均可使用
# 或使用 unsqueeze：
result = torch.from_numpy(ego_current).unsqueeze(1)  # PyTorch

print(result.size(), result)

torch.Size([3, 1]) tensor([[1],
        [2],
        [3]])


In [4]:
import torch

# 创建一个形状为 [2, 3] 的张量
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)

# 沿第1维求平均（即对每一行的元素求平均）
result = torch.mean(x, dim=1)

print("原始张量 x:\n", x)
print("形状:", x.shape)  # 输出: torch.Size([2, 3])
print("\n处理后的张量:\n", result)
print("形状:", result.shape)  # 输出: torch.Size([2])
# 结果: tensor([2., 5.])


原始张量 x:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
形状: torch.Size([2, 3])

处理后的张量:
 tensor([2., 5.])
形状: torch.Size([2])


In [12]:
import torch
a = torch.randint(0,12,(12,2))
b = a.chunk(6, dim=0)
print('a: ',a, a.size())
print('b: ',b)
print('b[0]',b[0].size())


a:  tensor([[ 3,  4],
        [ 0,  3],
        [ 9,  6],
        [ 1,  3],
        [ 6,  5],
        [ 2,  9],
        [ 4,  4],
        [ 4,  8],
        [ 5,  0],
        [ 9,  2],
        [11,  8],
        [ 1,  4]]) torch.Size([12, 2])
b:  (tensor([[3, 4],
        [0, 3]]), tensor([[9, 6],
        [1, 3]]), tensor([[6, 5],
        [2, 9]]), tensor([[4, 4],
        [4, 8]]), tensor([[5, 0],
        [9, 2]]), tensor([[11,  8],
        [ 1,  4]]))
b[0] torch.Size([2, 2])
